// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelAiDifficultyDataType
{
    public string id;  // ID
    public string name;  // UI显示名称
    public string rankMin;  // 段位下限
    public string rankMax;  // 段位上限
    public string humanSLProfile;  // KataGo人类风格Profile
    public bool useHumanPolicy;  // 使用HumanPolicy
    public bool includePolicy;  // 包含Policy输出
    public int maxVisits;  // 最大访问次数
    public int candidateLimit;  // 候选点数量
    public float mistakeRate;  // 失误概率
    public float temperature;  // 采样温度
    public float maxScoreLoss;  // 最大亏损目数
    public float visitPower;  // 访问权重指数
    public bool allowPassBeforeEndgame;  // 终局前允许Pass
    public int thinkDelayMs;  // AI思考延迟毫秒
    public int realtimeMaxVisits9;  // 9路实时访问上限
    public int realtimeMaxVisits13;  // 13路实时访问上限
    public int realtimeMaxVisits19;  // 19路实时访问上限
    public int candidateLimit9;  // 9路候选点数量
    public int candidateLimit13;  // 13路候选点数量
    public int candidateLimit19;  // 19路候选点数量
    public float maxScoreLoss9;  // 9路最大亏损目数
    public float maxScoreLoss13;  // 13路最大亏损目数
    public float maxScoreLoss19;  // 19路最大亏损目数
    public bool dynamicBudgetEnabled;  // 动态预算开关
    public int probeMaxVisits9;  // 9路探测访问次数
    public int probeMaxVisits13;  // 13路探测访问次数
    public int probeMaxVisits19;  // 19路探测访问次数
    public int openingProbeMoveLimit9;  // 9路开局探测手数
    public int openingProbeMoveLimit13;  // 13路开局探测手数
    public int openingProbeMoveLimit19;  // 19路开局探测手数
    public float closeScoreLeadThreshold9;  // 9路接近局势目差阈值
    public float closeScoreLeadThreshold13;  // 13路接近局势目差阈值
    public float closeScoreLeadThreshold19;  // 19路接近局势目差阈值
    public float closeWinrateThreshold9;  // 9路接近胜率阈值
    public float closeWinrateThreshold13;  // 13路接近胜率阈值
    public float closeWinrateThreshold19;  // 19路接近胜率阈值
    public float simpleCandidateGapThreshold9;  // 9路简单候选差距阈值
    public float simpleCandidateGapThreshold13;  // 13路简单候选差距阈值
    public float simpleCandidateGapThreshold19;  // 19路简单候选差距阈值
    public float confidentBestMoveGapThreshold9;  // 9路明显首选差距阈值
    public float confidentBestMoveGapThreshold13;  // 13路明显首选差距阈值
    public float confidentBestMoveGapThreshold19;  // 19路明显首选差距阈值
    public int forceFullBudgetMoveLimit9;  // 9路强制完整预算手数
    public int forceFullBudgetMoveLimit13;  // 13路强制完整预算手数
    public int forceFullBudgetMoveLimit19;  // 19路强制完整预算手数
    public int probeMinMoveInfoCount;  // 探测最小候选数量

    public static Dictionary<string, DuelAiDifficultyDataType> DuelAiDifficultyDict;

    public static DuelAiDifficultyDataType GetConfigData(string id)
    {
        if (DuelAiDifficultyDict == null) {
            DuelAiDifficultyDict = new Dictionary<string, DuelAiDifficultyDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_ai_difficulty");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelAiDifficultyDataType>();
                        DuelAiDifficultyDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelAiDifficultyDict.TryGetValue(id, out DuelAiDifficultyDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
