// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelAiDifficultyDataType
{
    public string id;  // ID
    public string name;  // UI显示名称
    public string rankMin;  // 段位下限
    public string rankMax;  // 段位上限
    public string humanSLProfile;  // KataGo人类风格Profile
    public bool useHumanPolicy;  // 使用HumanPolicy
    public bool includePolicy;  // 包含Policy输出
    public int maxVisits;  // 最大访问次数
    public int candidateLimit;  // 候选点数量
    public float mistakeRate;  // 失误概率
    public float temperature;  // 采样温度
    public float maxScoreLoss;  // 最大亏损目数
    public float visitPower;  // 访问权重指数
    public bool allowPassBeforeEndgame;  // 终局前允许Pass
    public int thinkDelayMs;  // AI思考延迟毫秒

    public static Dictionary<string, DuelAiDifficultyDataType> DuelAiDifficultyDict;

    public static DuelAiDifficultyDataType GetConfigData(string id)
    {
        if (DuelAiDifficultyDict == null) {
            DuelAiDifficultyDict = new Dictionary<string, DuelAiDifficultyDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_ai_difficulty");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelAiDifficultyDataType>();
                        DuelAiDifficultyDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelAiDifficultyDict.TryGetValue(id, out DuelAiDifficultyDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
