if(TARGET katago_zlib)
  set(ZLIB_FOUND TRUE)
  set(ZLIB_INCLUDE_DIRS "${ZLIB_SOURCE_DIR}")
  set(ZLIB_INCLUDE_DIR "${ZLIB_SOURCE_DIR}")
  set(ZLIB_LIBRARIES katago_zlib)
  set(ZLIB_LIBRARY katago_zlib)
else()
  set(ZLIB_FOUND FALSE)
endif()
