// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/LanRoomItemWidgetUI.cs
using TMPro;
using UnityEngine.UI;

public class LanRoomItemWidgetUI : UIBinderBase
{
    public Button btn_room;
    public TextMeshProUGUI txt_room;
}
