// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN-2/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/LanRoomItemWidgetUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class LanRoomItemWidgetUI : UIBinderBase
{
	public Button btn_room;
	public TextMeshProUGUI txt_room;
	public TextMeshProUGUI txt_room_name;
	public TextMeshProUGUI txt_player_count;
	public TextMeshProUGUI txt_host;
	public TextMeshProUGUI txt_config;
	public TextMeshProUGUI txt_endpoint;
	public TextMeshProUGUI txt_join_hint;
}