// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/OgsFriendItemWidgetUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class OgsFriendItemWidgetUI : UIBinderBase
{
	public Button btn_item;
	public Image img_avatar;
	public TextMeshProUGUI txt_username;
	public TextMeshProUGUI txt_meta;
	public TextMeshProUGUI txt_rating;
	public TextMeshProUGUI txt_status;
	public Button btn_profile;
	public Button btn_accept;
	public Button btn_reject;
	public StateRoot sr_row_mode;
	
	public enum SrRowModeState
	{
		Normal = 0,
		Invitation = 1,
	}
	
	public void SetSrRowModeState(SrRowModeState state, bool force = false)
	{
		if (sr_row_mode != null) {
			sr_row_mode.SetState((int)state, force);
		}
	}
}