// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/OgsFriendItemWidgetUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class OgsFriendItemWidgetUI : UIBinderBase
{
    public Button btn_item;
    public Image img_avatar;
    public TextMeshProUGUI txt_username;
    public TextMeshProUGUI txt_meta;
    public TextMeshProUGUI txt_rating;
    public TextMeshProUGUI txt_status;
    public Button btn_profile;
}
