// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN-2/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/ReplayArchiveItemWidgetUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class ReplayArchiveItemWidgetUI : UIBinderBase
{
	public Button btn_item;
	public TextMeshProUGUI txt_title;
	public TextMeshProUGUI txt_meta;
	public TextMeshProUGUI txt_result;
	public TextMeshProUGUI txt_status;
}