// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelByoyomiCountDataType
{
    public string id;  // ID
    public string displayName;  // 显示名称
    public int count;  // 读秒次数
    public bool ogsEnabled;  // OGS启用

    public static Dictionary<string, DuelByoyomiCountDataType> DuelByoyomiCountDict;

    public static DuelByoyomiCountDataType GetConfigData(string id)
    {
        if (DuelByoyomiCountDict == null) {
            DuelByoyomiCountDict = new Dictionary<string, DuelByoyomiCountDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_byoyomi_count");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelByoyomiCountDataType>();
                        DuelByoyomiCountDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelByoyomiCountDict.TryGetValue(id, out DuelByoyomiCountDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
