// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class LanRoomConfigDataType
{
    public string key;  // key
    public string remark;  // 备注
    public string value;  // 值

    public static Dictionary<string, LanRoomConfigDataType> LanRoomConfigDict;

    public static LanRoomConfigDataType GetConfigData(string id)
    {
        if (LanRoomConfigDict == null) {
            LanRoomConfigDict = new Dictionary<string, LanRoomConfigDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("lan_room_config");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<LanRoomConfigDataType>();
                        LanRoomConfigDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (LanRoomConfigDict.TryGetValue(id, out LanRoomConfigDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
