// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class ChessBoardDataType
{
    public string id;  // id
    public int boardSize;  // 棋盘大小
    public float vcamYOffset;  // 相机y轴额外偏移
    public bool ogsEnabled;  // OGS启用

    public static Dictionary<string, ChessBoardDataType> ChessBoardDict;

    public static ChessBoardDataType GetConfigData(string id)
    {
        if (ChessBoardDict == null) {
            ChessBoardDict = new Dictionary<string, ChessBoardDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("chess_board");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<ChessBoardDataType>();
                        ChessBoardDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (ChessBoardDict.TryGetValue(id, out ChessBoardDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
