// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/ConfirmPopupUI.cs
using TMPro;
using UnityEngine.UI;

public class ConfirmPopupUI : UIBinderBase
{
    public TextMeshProUGUI txt_title;
    public TextMeshProUGUI txt_content;
    public TextMeshProUGUI txt_confirm;
    public TextMeshProUGUI txt_cancel;
    public Button btn_confirm;
    public Button btn_cancel;
}
