// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/ConfirmPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class ConfirmPopupUI : UIBinderBase
{
	public TextMeshProUGUI txt_title;
	public TextMeshProUGUI txt_content;
	public TextMeshProUGUI txt_confirm;
	public TextMeshProUGUI txt_cancel;
	public Button btn_confirm;
	public Button btn_cancel;
	public TMP_InputField input_content;
	public StateRoot sr_platform;
	public StateRoot sr_dialog_layout;
	public StateRoot sr_dialog_buttons;
	
	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}
	
	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}
	
	public enum SrDialogLayoutState
	{
		Landscape = 0,
		Portrait = 1,
		ScoreLandscape = 2,
		ScorePortrait = 3,
	}
	
	public void SetSrDialogLayoutState(SrDialogLayoutState state, bool force = false)
	{
		if (sr_dialog_layout != null) {
			sr_dialog_layout.SetState((int)state, force);
		}
	}
	
	public enum SrDialogButtonsState
	{
		Both = 0,
		ConfirmOnly = 1,
		CancelOnly = 2,
		Neither = 3,
	}
	
	public void SetSrDialogButtonsState(SrDialogButtonsState state, bool force = false)
	{
		if (sr_dialog_buttons != null) {
			sr_dialog_buttons.SetState((int)state, force);
		}
	}
}