// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelSetupPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DuelSetupPopupUI : UIBinderBase
{
	public StateRoot sr_platform;
	public StateRoot sr_mode;
	public Button btn_9x9;
	public Button btn_13x13;
	public Button btn_19x19;
	public Button btn_start;
	public Button btn_close;
	public GameObject panel_ai_difficulty;
	public TMP_Dropdown dropdown_ai_difficulty;
	public GameObject panel_player_color;
	public TMP_Dropdown dropdown_player_color;
	public TMP_Dropdown dropdown_handicap;
	public TMP_Dropdown dropdown_ogs_time_option;
	public TMP_Dropdown dropdown_hold_time;
	public TMP_Dropdown dropdown_byoyomi_count;
	public TMP_Dropdown dropdown_byoyomi_time;
	
	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}
	
	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}
	
	public enum SrModeState
	{
		Local = 0,
		Ai = 1,
		Lan = 2,
		Ogs = 3,
		FreeLayout = 4,
	}
	
	public void SetSrModeState(SrModeState state, bool force = false)
	{
		if (sr_mode != null) {
			sr_mode.SetState((int)state, force);
		}
	}
}