// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelMoveConfirmPopupUI.cs
using UnityEngine.UI;

public class DuelMoveConfirmPopupUI : UIBinderBase
{
    public Button btn_confirm;
    public Button btn_cancel;
    public Button btn_move_up;
    public Button btn_move_down;
    public Button btn_move_left;
    public Button btn_move_right;
}
