// This file was automatically generated by UICodeGenerator.cs
// F:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelPageUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DuelPageUI : UIBinderBase
{
	public GameObject panel_black_player;
	public TextMeshProUGUI txt_black_title;
	public TextMeshProUGUI txt_black_hold_time;
	public TextMeshProUGUI txt_black_byoyomi_count;
	public TextMeshProUGUI txt_black_byoyomi_time;
	public GameObject panel_white_player;
	public TextMeshProUGUI txt_white_title;
	public TextMeshProUGUI txt_white_hold_time;
	public TextMeshProUGUI txt_white_byoyomi_count;
	public TextMeshProUGUI txt_white_byoyomi_time;
	public Button btn_duel_settings;
	public Button btn_duel_ownership;
	public TextMeshProUGUI txt_duel_ownership_button;
	public GameObject panel_duel_ownership_result;
	public TextMeshProUGUI txt_ownership_black_points;
	public TextMeshProUGUI txt_ownership_white_points;
	public GameObject panel_duel_settings;
	public Button btn_settings_save;
	public Button btn_settings_exit;
	public Button btn_settings_close;
}
