// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelSetupPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DuelSetupPopupUI : UIBinderBase
{
	public Button btn_9x9;
	public Button btn_13x13;
	public Button btn_19x19;
	public Button btn_hold_time_2m;
	public Button btn_hold_time_5m;
	public Button btn_hold_time_10m;
	public Button btn_hold_time_20m;
	public Button btn_hold_time_infinite;
	public Button btn_byoyomi_count_off;
	public Button btn_byoyomi_count_1;
	public Button btn_byoyomi_count_3;
	public Button btn_byoyomi_count_5;
	public Button btn_byoyomi_time_10s;
	public Button btn_byoyomi_time_20s;
	public Button btn_byoyomi_time_30s;
	public Button btn_byoyomi_time_60s;
	public Button btn_start;
	public Button btn_close;
	public GameObject panel_ai_difficulty;
	public TMP_Dropdown dropdown_ai_difficulty;
	public GameObject panel_player_color;
	public TMP_Dropdown dropdown_player_color;
	public TMP_Dropdown dropdown_handicap;
}