// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/LanRoomPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class LanRoomPopupUI : UIBinderBase
{
	public Button btn_create_room;
	public Button btn_search_room;
	public Button btn_close;
	public GameObject panel_room_list;
	public TextMeshProUGUI txt_status;
	public RectTransform content_room_list;
	public StateRoot sr_platform;
	
	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}
	
	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}
}