// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/LoadingPageUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class LoadingPageUI : UIBinderBase
{
	public TextMeshProUGUI txt_loading;
	public TextMeshProUGUI txt_detail;
	public TextMeshProUGUI txt_percent;
	public Image img_progress_fill;
	public StateRoot sr_platform;
	
	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}
	
	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}
}