// This file was automatically generated by UICodeGenerator.cs
// F:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/LoadingPageUI.cs
using TMPro;
using UnityEngine.UI;

public class LoadingPageUI : UIBinderBase
{
	public TextMeshProUGUI txt_loading;
	public TextMeshProUGUI txt_detail;
	public TextMeshProUGUI txt_percent;
	public Image img_progress_fill;
}
