// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/MainMenuPageUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class MainMenuPageUI : UIBinderBase
{
	public Button btn_continue;
	public Button btn_new_game;
	public Button btn_ai_game;
	public Button btn_exit;
	public Button btn_user_info;
}
