// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN-2/UnityProject/Assets/Scripts/Game/UI/Binder/Page/MainMenuPageUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class MainMenuPageUI : UIBinderBase
{
	public StateRoot sr_platform;
	public Button btn_new_game;
	public Button btn_exit;
	public Button btn_user_info;
	public Button btn_ai_game;
	public Button btn_lan_game;
}
