// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/OgsFriendListPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class OgsFriendListPopupUI : UIBinderBase
{
    public RectTransform panel_root;
    public StateRoot sr_platform;
    public StateRoot sr_ogs_friend_state;
    public Button btn_close;
    public Button btn_refresh;
    public Button btn_add_friend;
    public Button btn_friend_requests;
    public Button btn_retry;
    public Button btn_login;
    public Button btn_prev_page;
    public Button btn_next_page;
    public TextMeshProUGUI txt_page;
    public TextMeshProUGUI txt_loading;
    public TextMeshProUGUI txt_empty;
    public TextMeshProUGUI txt_error;
    public RectTransform content_friend_list;

    public enum SrPlatformState
    {
        Landscape = 0,
        Portrait = 1,
    }

    public void SetSrPlatformState(SrPlatformState state, bool force = false)
    {
        if (sr_platform != null) {
            sr_platform.SetState((int)state, force);
        }
    }

    public enum SrOgsFriendState
    {
        NotLoggedIn = 0,
        Loading = 1,
        Empty = 2,
        Error = 3,
        Content = 4,
    }

    public void SetSrOgsFriendState(SrOgsFriendState state, bool force = false)
    {
        if (sr_ogs_friend_state != null) {
            sr_ogs_friend_state.SetState((int)state, force);
        }
    }
}
