// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/RecentReplayListPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class RecentReplayListPopupUI : UIBinderBase
{
    public RectTransform panel_root;
    public StateRoot sr_platform;
    public StateRoot sr_recent_replay_state;
    public Button btn_close;
    public Button btn_refresh;
    public Button btn_retry;
    public Button btn_prev_page;
    public Button btn_next_page;
    public TextMeshProUGUI txt_page;
    public TextMeshProUGUI txt_loading;
    public TextMeshProUGUI txt_empty;
    public TextMeshProUGUI txt_error;
    public RectTransform content_replay_list;

    public enum SrPlatformState
    {
        Landscape = 0,
        Portrait = 1,
    }

    public void SetSrPlatformState(SrPlatformState state, bool force = false)
    {
        if (sr_platform != null) {
            sr_platform.SetState((int)state, force);
        }
    }

    public enum SrRecentReplayState
    {
        Loading = 0,
        Empty = 1,
        Error = 2,
        Content = 3,
    }

    public void SetSrRecentReplayState(SrRecentReplayState state, bool force = false)
    {
        if (sr_recent_replay_state != null) {
            sr_recent_replay_state.SetState((int)state, force);
        }
    }
}
