// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/UserInfoPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoPopupUI : UIBinderBase
{
	public RectTransform panel_root;
	public StateRoot sr_platform;
	public TextMeshProUGUI txt_user_id;
	public TextMeshProUGUI txt_win_count;
	public TextMeshProUGUI txt_lose_count;
	public Button btn_close;
	public TextMeshProUGUI txt_save_tip;
	public TextMeshProUGUI txt_user_name;
	public Button btn_edit_name;
	public TextMeshProUGUI txt_replay_page;
	public TextMeshProUGUI txt_replay_empty;
	public Button btn_replay_prev;
	public Button btn_replay_next;
	public RectTransform content_replay_list;
	public Button btn_login_ogs;
	public StateRoot sr_ogs_account;
	public Image img_ogs_avatar;
	public TextMeshProUGUI txt_ogs_username;
	public TextMeshProUGUI txt_ogs_id;
	public TextMeshProUGUI txt_ogs_country;
	public TextMeshProUGUI txt_ogs_registered;
	public TextMeshProUGUI txt_ogs_tags;
	public TextMeshProUGUI txt_ogs_about;
	public TextMeshProUGUI txt_ogs_rating_overall;
	public TextMeshProUGUI txt_ogs_ranking;
	public TextMeshProUGUI txt_ogs_rating_19;
	public TextMeshProUGUI txt_ogs_rating_13;
	public TextMeshProUGUI txt_ogs_rating_9;
	public Button btn_ogs_refresh;
	public Button btn_ogs_logout;
	public TextMeshProUGUI txt_ogs_loading;
	public TextMeshProUGUI txt_ogs_error;
	public Button btn_ogs_retry;
	public TextMeshProUGUI txt_ogs_friend_summary;
	public Button btn_open_ogs_friends;
	public RectTransform red_dot_ogs_friends;
	public TextMeshProUGUI txt_recent_replays_summary;
	public Button btn_open_recent_replays;

	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}

	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}

	public enum SrOgsAccountState
	{
		LoggedOut = 0,
		LoggedIn = 1,
		Loading = 2,
		Error = 3,
	}

	public void SetSrOgsAccountState(SrOgsAccountState state, bool force = false)
	{
		if (sr_ogs_account != null) {
			sr_ogs_account.SetState((int)state, force);
		}
	}
}
