// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/UserInfoPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoPopupUI : UIBinderBase
{
	public TextMeshProUGUI txt_user_id;
	public TextMeshProUGUI txt_user_name;
	public TextMeshProUGUI txt_win_count;
	public TextMeshProUGUI txt_lose_count;
	public TextMeshProUGUI txt_save_tip;
	public TextMeshProUGUI txt_replay_page;
	public TextMeshProUGUI txt_replay_empty;
	public Button btn_edit_name;
	public Button btn_replay_prev;
	public Button btn_replay_next;
	public Button btn_close;
	public RectTransform content_replay_list;
}
