// This file was automatically generated by UICodeGenerator.cs
// F:/WorkSpace/WeiqiXN-2/UnityProject/Assets/Scripts/Game/UI/Binder/Page/UserInfoPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoPopupUI : UIBinderBase
{
	public RectTransform panel_root;
	public StateRoot sr_platform;
	public TextMeshProUGUI txt_user_id;
	public TextMeshProUGUI txt_win_count;
	public TextMeshProUGUI txt_lose_count;
	public Button btn_close;
	public TextMeshProUGUI txt_save_tip;
	public TextMeshProUGUI txt_user_name;
	public Button btn_edit_name;
	public TextMeshProUGUI txt_replay_page;
	public TextMeshProUGUI txt_replay_empty;
	public Button btn_replay_prev;
	public Button btn_replay_next;
	public RectTransform content_replay_list;
	public Button btn_login_ogs;
	
	public enum SrPlatformState
	{
		Landscape = 0,
		Portrait = 1,
	}
	
	public void SetSrPlatformState(SrPlatformState state, bool force = false)
	{
		if (sr_platform != null) {
			sr_platform.SetState((int)state, force);
		}
	}
}