// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class GamePrefabDataType
{
    public string id;  // id
    public string resPath;  // prefab资源路径

    public static Dictionary<string, GamePrefabDataType> GamePrefabDict;

    public static GamePrefabDataType GetConfigData(string id)
    {
        if (GamePrefabDict == null) {
            GamePrefabDict = new Dictionary<string, GamePrefabDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("game_prefab");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<GamePrefabDataType>();
                        GamePrefabDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (GamePrefabDict.TryGetValue(id, out GamePrefabDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
