// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class OgsAutomatchTimeOptionDataType
{
    public string id;  // ID
    public string boardCfgId;  // 棋盘配置
    public string displayName;  // 显示名称
    public string speed;  // OGS速度
    public string system;  // OGS计时系统
    public string holdTimeCfgId;  // 持有时间配置
    public string byoyomiCountCfgId;  // 读秒次数配置
    public string byoyomiTimeCfgId;  // 读秒时间配置
    public int sortOrder;  // 排序
    public bool enabled;  // 启用

    public static Dictionary<string, OgsAutomatchTimeOptionDataType> OgsAutomatchTimeOptionDict;

    public static OgsAutomatchTimeOptionDataType GetConfigData(string id)
    {
        if (OgsAutomatchTimeOptionDict == null) {
            OgsAutomatchTimeOptionDict = new Dictionary<string, OgsAutomatchTimeOptionDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("ogs_automatch_time_option");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<OgsAutomatchTimeOptionDataType>();
                        OgsAutomatchTimeOptionDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (OgsAutomatchTimeOptionDict.TryGetValue(id, out OgsAutomatchTimeOptionDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
