// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class OgsConfigDataType
{
    public string key;  // key
    public string remark;  // remark
    public string value;  // value

    public static Dictionary<string, OgsConfigDataType> OgsConfigDict;

    public static OgsConfigDataType GetConfigData(string id)
    {
        if (OgsConfigDict == null) {
            OgsConfigDict = new Dictionary<string, OgsConfigDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("ogs_config");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<OgsConfigDataType>();
                        OgsConfigDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (OgsConfigDict.TryGetValue(id, out OgsConfigDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
