// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class UiPageDataType
{
    public string id;  // id
    public string contextType;  // 所在context层级
    public bool isPopup;  // 是否为弹窗
    public bool isLoadAsync;  // 是否异步加载
    public bool closeOnSceneExit;  // 场景退出时关闭

    public static Dictionary<string, UiPageDataType> UiPageDict;

    public static UiPageDataType GetConfigData(string id)
    {
        if (UiPageDict == null) {
            UiPageDict = new Dictionary<string, UiPageDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("ui_page");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<UiPageDataType>();
                        UiPageDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (UiPageDict.TryGetValue(id, out UiPageDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
