// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class MessageDataType
{
    public string id;  // ID
    public string text;  // 文案
    public string remark;  // 备注

    public static Dictionary<string, MessageDataType> MessageDict;

    public static MessageDataType GetConfigData(string id)
    {
        if (MessageDict == null) {
            MessageDict = new Dictionary<string, MessageDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("message");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<MessageDataType>();
                        MessageDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (MessageDict.TryGetValue(id, out MessageDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
