// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelHandicapDataType
{
    public string id;  // ID
    public string boardCfgId;  // 棋盘配置
    public string displayName;  // 显示名称
    public int handicapCount;  // 让子数
    public float komi;  // 贴目
    public string[] stonePoints;  // 星位坐标
    public bool ogsEnabled;  // OGS启用

    public static Dictionary<string, DuelHandicapDataType> DuelHandicapDict;

    public static DuelHandicapDataType GetConfigData(string id)
    {
        if (DuelHandicapDict == null) {
            DuelHandicapDict = new Dictionary<string, DuelHandicapDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_handicap");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelHandicapDataType>();
                        DuelHandicapDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelHandicapDict.TryGetValue(id, out DuelHandicapDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
