// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class ReplayConfigDataType
{
    public string id;  // ID
    public string group;  // 参数分组
    public string valueType;  // 值类型
    public int intValue;  // 整数值
    public float floatValue;  // 浮点值
    public string stringValue;  // 字符串值
    public bool boolValue;  // 布尔值
    public string description;  // 说明

    public static Dictionary<string, ReplayConfigDataType> ReplayConfigDict;

    public static ReplayConfigDataType GetConfigData(string id)
    {
        if (ReplayConfigDict == null) {
            ReplayConfigDict = new Dictionary<string, ReplayConfigDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("replay_config");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<ReplayConfigDataType>();
                        ReplayConfigDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (ReplayConfigDict.TryGetValue(id, out ReplayConfigDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
