// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class RuntimeAssetDataType
{
    public string id;  // id
    public string assetType;  // 资源类型
    public string resPath;  // 资源路径
    public string bundleName;  // AssetBundle名

    public static Dictionary<string, RuntimeAssetDataType> RuntimeAssetDict;

    public static RuntimeAssetDataType GetConfigData(string id)
    {
        if (RuntimeAssetDict == null) {
            RuntimeAssetDict = new Dictionary<string, RuntimeAssetDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("runtime_asset");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<RuntimeAssetDataType>();
                        RuntimeAssetDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (RuntimeAssetDict.TryGetValue(id, out RuntimeAssetDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
