// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelHoldTimeDataType
{
    public string id;  // ID
    public string displayName;  // 显示名称
    public int holdSeconds;  // 持有秒数
    public bool isInfinite;  // 是否无限时间
    public bool ogsEnabled;  // OGS启用

    public static Dictionary<string, DuelHoldTimeDataType> DuelHoldTimeDict;

    public static DuelHoldTimeDataType GetConfigData(string id)
    {
        if (DuelHoldTimeDict == null) {
            DuelHoldTimeDict = new Dictionary<string, DuelHoldTimeDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_hold_time");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelHoldTimeDataType>();
                        DuelHoldTimeDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelHoldTimeDict.TryGetValue(id, out DuelHoldTimeDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
