// This file is auto generated by config exporter
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using XNClient.Logger;

public class DuelByoyomiTimeDataType
{
    public string id;  // ID
    public string displayName;  // 显示名称
    public int seconds;  // 读秒秒数
    public bool ogsEnabled;  // OGS启用

    public static Dictionary<string, DuelByoyomiTimeDataType> DuelByoyomiTimeDict;

    public static DuelByoyomiTimeDataType GetConfigData(string id)
    {
        if (DuelByoyomiTimeDict == null) {
            DuelByoyomiTimeDict = new Dictionary<string, DuelByoyomiTimeDataType>();
            var jsonObj = GlobalConfig.GetJsonConfigJObject("duel_byoyomi_time");
            if (jsonObj != null) {
                foreach (var property in jsonObj.Properties()) {
                    try {
                        var item = property.Value.ToObject<DuelByoyomiTimeDataType>();
                        DuelByoyomiTimeDict[property.Name] = item;
                    }
                    catch (Exception ex) {
                        XNLogger.LogError($"读表错误，跳过条目 {property.Name}: {ex.Message}");
                    }
                }
            }
        }
        if (DuelByoyomiTimeDict.TryGetValue(id, out DuelByoyomiTimeDataType data)) {
            return data;
        } else {
            return null;
        }
    }
}
