using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using XNLogger = XNClient.Logger.XNLogger;

public static class UICodeGenerator
{
    private static readonly HashSet<string> CSharpKeywords = new HashSet<string>
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
        "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
        "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
        "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new",
        "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
        "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static",
        "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong",
        "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
    };

    public static void ExportUIScripts(UIBinderEditor uibinderEditor)
    {
        ExportUIBinder(uibinderEditor);
        if (!File.Exists(uibinderEditor.logicExportPath)) {
            ExportUILogic(uibinderEditor);
        }

        AssetDatabase.Refresh();
    }

    private static void ExportUIBinder(UIBinderEditor uiBinderEditor)
    {
        if (File.Exists(uiBinderEditor.binderExportPath)) File.Delete(uiBinderEditor.binderExportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(uiBinderEditor.binderExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UICodeGenerator.cs");
        generator.AddLine($"// {uiBinderEditor.binderExportPath.Replace('\\', '/')}");
        generator.AddLine("using TMPro;");
        generator.AddLine("using UnityEngine;");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBlock($"public class {uiBinderEditor.binderClsName} : UIBinderBase")) {
            var uiBinderTypes = TypeCache.GetTypesDerivedFrom(typeof(UIBinderBase));
            var uiLogicTypes = TypeCache.GetTypesDerivedFrom(typeof(UILogicBase));
            List<(string, UIBinderEditor)> widgetBinderEditors = new List<(string, UIBinderEditor)>();
            List<(string, StateRoot)> stateRoots = new List<(string, StateRoot)>();
            foreach (var node in uiBinderEditor.nodeList) {
                if (node.value is UIBinderEditor childBinderEditor) {
                    Type binderType = uiBinderTypes.FirstOrDefault(t => t.Name == childBinderEditor.binderClsName);
                    Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == childBinderEditor.logicClsName);
                    if (binderType != null && logicType != null && childBinderEditor.GetComponent(binderType) != null) {
                        generator.AddLine($"public UIBinderEditor _{node.name};");
                        generator.AddLine($"public {logicType.Name} {node.name};");
                        widgetBinderEditors.Add((node.name, childBinderEditor));
                    } else {
                        XNLogger.LogError("Child widget binder script not attached!", ("widgetLogicType", logicType.Name));
                    }
                } else {
                    generator.AddLine($"public {node.value.GetType().Name} {node.name};");
                    if (node.value is StateRoot stateRoot) {
                        stateRoots.Add((node.name, stateRoot));
                    }
                }
            }

            foreach (var (fieldName, stateRoot) in stateRoots) {
                ExportStateRootAccessors(generator, fieldName, stateRoot);
            }

            if (widgetBinderEditors.Count > 0) {
                generator.AddLine();
                using (generator.AddBlock($"public override void InitWidgets(UILogicBase owner)")) {
                    generator.AddLine("base.InitWidgets(owner);");
                    foreach (var (fieldName, binder) in widgetBinderEditors) {
                        Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == binder.logicClsName);
                        if (logicType != null) {
                            generator.AddLine($"{fieldName} = UIWidget.CreateWidgetInstance<{binder.logicClsName}>(owner);");
                            generator.AddLine($"binderWidgets.TryAdd(_{fieldName}.name, {fieldName});");
                            generator.AddLine($"binderWidgetGOs.TryAdd(_{fieldName}.name, _{fieldName}.gameObject);");
                        }
                    }
                }
            }
        }

        using (var writer = new StreamWriter(uiBinderEditor.binderExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }

    private static void ExportStateRootAccessors(CSCodeGenerator generator, string fieldName, StateRoot stateRoot)
    {
        string stateEnumName = $"{ToPascalIdentifier(fieldName, "StateRoot")}State";
        string setStateMethodName = $"Set{ToPascalIdentifier(fieldName, "StateRoot")}State";

        generator.AddLine();
        using (generator.AddBlock($"public enum {stateEnumName}")) {
            HashSet<string> memberNames = new HashSet<string>();
            for (int i = 0; i < stateRoot.States.Count; i++) {
                string memberName = ToUniqueIdentifier(ToPascalIdentifier(stateRoot.States[i].name, $"State{i}"), memberNames);
                generator.AddLine($"{memberName} = {i},");
            }
        }

        generator.AddLine();
        using (generator.AddBlock($"public void {setStateMethodName}({stateEnumName} state, bool force = false)")) {
            generator.AddLine($"if ({fieldName} != null) {{");
            generator.lineStartTabs++;
            generator.AddLine($"{fieldName}.SetState((int)state, force);");
            generator.lineStartTabs--;
            generator.AddLine("}");
        }
    }

    private static string ToUniqueIdentifier(string identifier, HashSet<string> usedIdentifiers)
    {
        string uniqueIdentifier = identifier;
        int suffix = 1;
        while (!usedIdentifiers.Add(uniqueIdentifier)) {
            uniqueIdentifier = $"{identifier}{suffix}";
            suffix++;
        }

        return uniqueIdentifier;
    }

    private static string ToPascalIdentifier(string value, string fallback)
    {
        StringBuilder builder = new StringBuilder();
        bool uppercaseNext = true;
        foreach (char c in value ?? string.Empty) {
            if (char.IsLetterOrDigit(c)) {
                builder.Append(uppercaseNext ? char.ToUpperInvariant(c) : c);
                uppercaseNext = false;
            } else {
                uppercaseNext = true;
            }
        }

        string identifier = builder.Length > 0 ? builder.ToString() : fallback;
        if (!char.IsLetter(identifier[0]) && identifier[0] != '_') {
            identifier = $"_{identifier}";
        }

        if (CSharpKeywords.Contains(identifier)) {
            identifier = $"_{identifier}";
        }

        return identifier;
    }

    private static void ExportUILogic(UIBinderEditor uiBinderEditor)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(uiBinderEditor.logicExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();

        if (uiBinderEditor.isPage) {
            using (generator.AddBlock($"public class {uiBinderEditor.logicClsName} : UIPageWithBinder<{uiBinderEditor.binderClsName}>")) {
                generator.AddLine($"public override string pageName => UIPage.GetPageName<{uiBinderEditor.logicClsName}>();");
            }
        } else {
            using (generator.AddBlock($"public class {uiBinderEditor.logicClsName} : UIWidgetWithBinder<{uiBinderEditor.binderClsName}>")) {
                generator.AddLine($"public override string widgetName => UIWidget.GetWidgetName<{uiBinderEditor.logicClsName}>();");
            }
        }

        using (var writer = new StreamWriter(uiBinderEditor.logicExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}

